:toc:

== thing 1
* This is a test
* Another
- something

[#free_the_world]#free the world#

[sidebar]
Sidebars are used to visually separate auxiliary bits of content
that supplement the main text.


== thing 2

.Optional Title
****
Sidebars are used to visually separate auxiliary bits of content
that supplement the main text.

TIP: They can contain any type of content.

.Source code block in a sidebar
[source,js]
----
const { expect, expectCalledWith, heredoc } = require('../test/test-utils')
----
****

[%collapsible]
====
This content is only revealed when the user `clicks` the block title.
====


[example%collapsible]
This content is only revealed when the user clicks the block title.

.Click to reveal the answer
[%collapsible]
====
This is the answer.
====

:experimental:
:stem: 
:kbd:

stem:[sqrt(4) = 2]


Select menu:View[Zoom > Reset] to reset the zoom level to the default setting.


A matrix can be written as stem:[[[a,b\],[c,d\]\]((n),(k))].

CPU:: The brain of the computer.
Hard drive:: Permanent storage for operating system and/or user files.
RAM:: Temporarily stores information the CPU uses during operation.
Keyboard:: Used to enter text or control items on the screen.
Mouse:: Used to point to and select items on your computer screen.
Monitor:: Displays information in visual form using text and graphics.

kbd:[Ctrl+T]

Open a new tab


[IMPORTANT] 
.Feeding the Werewolves
==== 
While werewolves are hardy community members, keep in mind the following dietary concerns:

. They are allergic to cinnamon.
. More than two glasses of orange juice in 24 hours makes them howl in harmony with alarms and sirens.
. Celery makes them sad.
====

