type PersonalPrefix {
    id: ID!
    Text: String!
    Abbr: [String!]
    Desc: String
}

type PersonalPrefixFormat {
    id: ID!
    Name: String!
    Description: String
}

type PersonalPrefixAssigned {
    prefix: PersonalPrefix!
    format: PersonalPrefixFormat
}

type PersonalSuffix {
    id: ID!
    Text: String!
    Abbr: [String!]
    Desc: String
}

type PersonalSuffixFormat {
    id: ID!
    Name: String!
    Description: String
}

type PersonalSuffixAssigned {
    suffix: PersonalSuffix!
    format: PersonalSuffixFormat
}

type PersonalNameFormat {
    id: ID!
    Name: String!
    Description: String
}

type PersonalName {
    id: ID!
    prefix: [PersonalPrefixAssigned!]
    first: [String!]
    middle: [String!]
    last: [String!]
    suffix: [PersonalSuffixAssigned!]
    format: PersonalNameFormat
}

input NewPersonalName {
    prefix: [PersonalPrefixAssigned!]
    first: [String!]
    middle: [String!]
    last: [String!]
    suffix: [PersonalSuffixAssigned!]
    format: PersonalNameFormat
}
