package time

import "time"

const (
	FORMAT_DATETIME = time.RFC3339
	FORMAT_TIME     = "15:04:05Z07:00"
	FORMAT_DATE     = "2006-01-02"

	SECONDS_PER_MINUTE = 60
	SECONDS_PER_HOUR   = 60 * SECONDS_PER_MINUTE
	SECONDS_PER_DAY    = 24 * SECONDS_PER_HOUR
	SECONDS_PER_WEEK   = 7 * SECONDS_PER_DAY
	SECONDS_PER_MONTH  = 4 * SECONDS_PER_WEEK
	SECONDS_PER_YEAR   = 12 * SECONDS_PER_MONTH
)
