//************************************************************************************
//*                                                                                  *
//* ===== DO NOT EDIT =====                                                          *
//* Manual changes will be overwritten.                                              *
//* Generated by github.com/boundedinfinity/enumer                                   *
//*                                                                                  *
//************************************************************************************

package location

import (
	"database/sql/driver"
	"encoding/xml"
	"fmt"

	"github.com/boundedinfinity/enumer"
)

type CountryAlpha3 string

// /////////////////////////////////////////////////////////////////
//  CountryAlpha3 Stringer implemenation
// /////////////////////////////////////////////////////////////////

func (t CountryAlpha3) String() string {
	return string(t)
}

// /////////////////////////////////////////////////////////////////
//  CountryAlpha3 JSON marshal/unmarshal implemenation
// /////////////////////////////////////////////////////////////////

func (t CountryAlpha3) MarshalJSON() ([]byte, error) {
	return enumer.MarshalJSON(t)
}

func (t *CountryAlpha3) UnmarshalJSON(data []byte) error {
	return enumer.UnmarshalJSON(data, t, CountryAlpha3s.Parse)
}

// /////////////////////////////////////////////////////////////////
//  CountryAlpha3 YAML marshal/unmarshal implemenation
// /////////////////////////////////////////////////////////////////

func (t CountryAlpha3) MarshalYAML() (interface{}, error) {
	return enumer.MarshalYAML(t)
}

func (t *CountryAlpha3) UnmarshalYAML(unmarshal func(interface{}) error) error {
	return enumer.UnmarshalYAML(unmarshal, t, CountryAlpha3s.Parse)
}

// /////////////////////////////////////////////////////////////////
//  CountryAlpha3 XML marshal/unmarshal implemenation
// /////////////////////////////////////////////////////////////////

func (t CountryAlpha3) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return enumer.MarshalXML(t, e, start)
}

func (t *CountryAlpha3) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return enumer.UnmarshalXML(t, CountryAlpha3s.Parse, d, start)
}

// /////////////////////////////////////////////////////////////////
//  CountryAlpha3 SQL Database marshal/unmarshal implemenation
// /////////////////////////////////////////////////////////////////

func (t CountryAlpha3) Value() (driver.Value, error) {
	return enumer.Value(t)
}

func (t *CountryAlpha3) Scan(value interface{}) error {
	return enumer.Scan(value, t, CountryAlpha3s.Parse)
}

// /////////////////////////////////////////////////////////////////
//
//  Enumeration
//
// /////////////////////////////////////////////////////////////////

type countryAlpha3s struct {
	AFG    CountryAlpha3
	ALA    CountryAlpha3
	ALB    CountryAlpha3
	DZA    CountryAlpha3
	ASM    CountryAlpha3
	AND    CountryAlpha3
	AGO    CountryAlpha3
	AIA    CountryAlpha3
	ATG    CountryAlpha3
	ARG    CountryAlpha3
	ARM    CountryAlpha3
	ABW    CountryAlpha3
	AUS    CountryAlpha3
	AUT    CountryAlpha3
	AZE    CountryAlpha3
	BHS    CountryAlpha3
	BHR    CountryAlpha3
	BGD    CountryAlpha3
	BRB    CountryAlpha3
	BLR    CountryAlpha3
	BEL    CountryAlpha3
	BLZ    CountryAlpha3
	BEN    CountryAlpha3
	BTN    CountryAlpha3
	BOL    CountryAlpha3
	BES    CountryAlpha3
	BIH    CountryAlpha3
	BWA    CountryAlpha3
	BVT    CountryAlpha3
	BRA    CountryAlpha3
	IOT    CountryAlpha3
	BRN    CountryAlpha3
	BGR    CountryAlpha3
	BFA    CountryAlpha3
	BDI    CountryAlpha3
	CPV    CountryAlpha3
	KHM    CountryAlpha3
	CMR    CountryAlpha3
	CAN    CountryAlpha3
	CYM    CountryAlpha3
	CAF    CountryAlpha3
	TCD    CountryAlpha3
	CHL    CountryAlpha3
	CHN    CountryAlpha3
	CXR    CountryAlpha3
	CCK    CountryAlpha3
	COL    CountryAlpha3
	COM    CountryAlpha3
	COG    CountryAlpha3
	COD    CountryAlpha3
	COK    CountryAlpha3
	CRI    CountryAlpha3
	CIV    CountryAlpha3
	HRV    CountryAlpha3
	CUB    CountryAlpha3
	CUW    CountryAlpha3
	CYP    CountryAlpha3
	CZE    CountryAlpha3
	DNK    CountryAlpha3
	DJI    CountryAlpha3
	DMA    CountryAlpha3
	DOM    CountryAlpha3
	ECU    CountryAlpha3
	EGY    CountryAlpha3
	SLV    CountryAlpha3
	GNQ    CountryAlpha3
	ERI    CountryAlpha3
	EST    CountryAlpha3
	SWZ    CountryAlpha3
	ETH    CountryAlpha3
	FLK    CountryAlpha3
	FRO    CountryAlpha3
	FJI    CountryAlpha3
	FIN    CountryAlpha3
	FRA    CountryAlpha3
	GUF    CountryAlpha3
	PYF    CountryAlpha3
	ATF    CountryAlpha3
	GAB    CountryAlpha3
	GMB    CountryAlpha3
	GEO    CountryAlpha3
	DEU    CountryAlpha3
	GHA    CountryAlpha3
	GIB    CountryAlpha3
	GRC    CountryAlpha3
	GRL    CountryAlpha3
	GRD    CountryAlpha3
	GLP    CountryAlpha3
	GUM    CountryAlpha3
	GTM    CountryAlpha3
	GGY    CountryAlpha3
	GIN    CountryAlpha3
	GNB    CountryAlpha3
	GUY    CountryAlpha3
	HTI    CountryAlpha3
	HMD    CountryAlpha3
	VAT    CountryAlpha3
	HND    CountryAlpha3
	HKG    CountryAlpha3
	HUN    CountryAlpha3
	ISL    CountryAlpha3
	IND    CountryAlpha3
	IDN    CountryAlpha3
	IRN    CountryAlpha3
	IRQ    CountryAlpha3
	IRL    CountryAlpha3
	IMN    CountryAlpha3
	ISR    CountryAlpha3
	ITA    CountryAlpha3
	JAM    CountryAlpha3
	JPN    CountryAlpha3
	JEY    CountryAlpha3
	JOR    CountryAlpha3
	KAZ    CountryAlpha3
	KEN    CountryAlpha3
	KIR    CountryAlpha3
	PRK    CountryAlpha3
	KOR    CountryAlpha3
	KWT    CountryAlpha3
	KGZ    CountryAlpha3
	LAO    CountryAlpha3
	LVA    CountryAlpha3
	LBN    CountryAlpha3
	LSO    CountryAlpha3
	LBR    CountryAlpha3
	LBY    CountryAlpha3
	LIE    CountryAlpha3
	LTU    CountryAlpha3
	LUX    CountryAlpha3
	MAC    CountryAlpha3
	MDG    CountryAlpha3
	MWI    CountryAlpha3
	MYS    CountryAlpha3
	MDV    CountryAlpha3
	MLI    CountryAlpha3
	MLT    CountryAlpha3
	MHL    CountryAlpha3
	MTQ    CountryAlpha3
	MRT    CountryAlpha3
	MUS    CountryAlpha3
	MYT    CountryAlpha3
	MEX    CountryAlpha3
	FSM    CountryAlpha3
	MDA    CountryAlpha3
	MCO    CountryAlpha3
	MNG    CountryAlpha3
	MNE    CountryAlpha3
	MSR    CountryAlpha3
	MAR    CountryAlpha3
	MOZ    CountryAlpha3
	MMR    CountryAlpha3
	NAM    CountryAlpha3
	NRU    CountryAlpha3
	NPL    CountryAlpha3
	NLD    CountryAlpha3
	NCL    CountryAlpha3
	NZL    CountryAlpha3
	NIC    CountryAlpha3
	NER    CountryAlpha3
	NGA    CountryAlpha3
	NIU    CountryAlpha3
	NFK    CountryAlpha3
	MKD    CountryAlpha3
	MNP    CountryAlpha3
	NOR    CountryAlpha3
	OMN    CountryAlpha3
	PAK    CountryAlpha3
	PLW    CountryAlpha3
	PSE    CountryAlpha3
	PAN    CountryAlpha3
	PNG    CountryAlpha3
	PRY    CountryAlpha3
	PER    CountryAlpha3
	PHL    CountryAlpha3
	PCN    CountryAlpha3
	POL    CountryAlpha3
	PRT    CountryAlpha3
	PRI    CountryAlpha3
	QAT    CountryAlpha3
	REU    CountryAlpha3
	ROU    CountryAlpha3
	RUS    CountryAlpha3
	RWA    CountryAlpha3
	BLM    CountryAlpha3
	SHN    CountryAlpha3
	KNA    CountryAlpha3
	LCA    CountryAlpha3
	MAF    CountryAlpha3
	SPM    CountryAlpha3
	VCT    CountryAlpha3
	WSM    CountryAlpha3
	SMR    CountryAlpha3
	STP    CountryAlpha3
	SAU    CountryAlpha3
	SEN    CountryAlpha3
	SRB    CountryAlpha3
	SYC    CountryAlpha3
	SLE    CountryAlpha3
	SGP    CountryAlpha3
	SXM    CountryAlpha3
	SVK    CountryAlpha3
	SVN    CountryAlpha3
	SLB    CountryAlpha3
	SOM    CountryAlpha3
	ZAF    CountryAlpha3
	SGS    CountryAlpha3
	SSD    CountryAlpha3
	ESP    CountryAlpha3
	LKA    CountryAlpha3
	SDN    CountryAlpha3
	SUR    CountryAlpha3
	SJM    CountryAlpha3
	SWE    CountryAlpha3
	CHE    CountryAlpha3
	SYR    CountryAlpha3
	TWN    CountryAlpha3
	TJK    CountryAlpha3
	TZA    CountryAlpha3
	THA    CountryAlpha3
	TLS    CountryAlpha3
	TGO    CountryAlpha3
	TKL    CountryAlpha3
	TON    CountryAlpha3
	TTO    CountryAlpha3
	TUN    CountryAlpha3
	TUR    CountryAlpha3
	TKM    CountryAlpha3
	TCA    CountryAlpha3
	TUV    CountryAlpha3
	UGA    CountryAlpha3
	UKR    CountryAlpha3
	ARE    CountryAlpha3
	GBR    CountryAlpha3
	UMI    CountryAlpha3
	USA    CountryAlpha3
	URY    CountryAlpha3
	UZB    CountryAlpha3
	VUT    CountryAlpha3
	VEN    CountryAlpha3
	VNM    CountryAlpha3
	VGB    CountryAlpha3
	VIR    CountryAlpha3
	WLF    CountryAlpha3
	ESH    CountryAlpha3
	YEM    CountryAlpha3
	ZMB    CountryAlpha3
	ZWE    CountryAlpha3
	Values []CountryAlpha3
	Err    error
}

var CountryAlpha3s = countryAlpha3s{
	AFG: CountryAlpha3("AFG"),
	ALA: CountryAlpha3("ALA"),
	ALB: CountryAlpha3("ALB"),
	DZA: CountryAlpha3("DZA"),
	ASM: CountryAlpha3("ASM"),
	AND: CountryAlpha3("AND"),
	AGO: CountryAlpha3("AGO"),
	AIA: CountryAlpha3("AIA"),
	ATG: CountryAlpha3("ATG"),
	ARG: CountryAlpha3("ARG"),
	ARM: CountryAlpha3("ARM"),
	ABW: CountryAlpha3("ABW"),
	AUS: CountryAlpha3("AUS"),
	AUT: CountryAlpha3("AUT"),
	AZE: CountryAlpha3("AZE"),
	BHS: CountryAlpha3("BHS"),
	BHR: CountryAlpha3("BHR"),
	BGD: CountryAlpha3("BGD"),
	BRB: CountryAlpha3("BRB"),
	BLR: CountryAlpha3("BLR"),
	BEL: CountryAlpha3("BEL"),
	BLZ: CountryAlpha3("BLZ"),
	BEN: CountryAlpha3("BEN"),
	BTN: CountryAlpha3("BTN"),
	BOL: CountryAlpha3("BOL"),
	BES: CountryAlpha3("BES"),
	BIH: CountryAlpha3("BIH"),
	BWA: CountryAlpha3("BWA"),
	BVT: CountryAlpha3("BVT"),
	BRA: CountryAlpha3("BRA"),
	IOT: CountryAlpha3("IOT"),
	BRN: CountryAlpha3("BRN"),
	BGR: CountryAlpha3("BGR"),
	BFA: CountryAlpha3("BFA"),
	BDI: CountryAlpha3("BDI"),
	CPV: CountryAlpha3("CPV"),
	KHM: CountryAlpha3("KHM"),
	CMR: CountryAlpha3("CMR"),
	CAN: CountryAlpha3("CAN"),
	CYM: CountryAlpha3("CYM"),
	CAF: CountryAlpha3("CAF"),
	TCD: CountryAlpha3("TCD"),
	CHL: CountryAlpha3("CHL"),
	CHN: CountryAlpha3("CHN"),
	CXR: CountryAlpha3("CXR"),
	CCK: CountryAlpha3("CCK"),
	COL: CountryAlpha3("COL"),
	COM: CountryAlpha3("COM"),
	COG: CountryAlpha3("COG"),
	COD: CountryAlpha3("COD"),
	COK: CountryAlpha3("COK"),
	CRI: CountryAlpha3("CRI"),
	CIV: CountryAlpha3("CIV"),
	HRV: CountryAlpha3("HRV"),
	CUB: CountryAlpha3("CUB"),
	CUW: CountryAlpha3("CUW"),
	CYP: CountryAlpha3("CYP"),
	CZE: CountryAlpha3("CZE"),
	DNK: CountryAlpha3("DNK"),
	DJI: CountryAlpha3("DJI"),
	DMA: CountryAlpha3("DMA"),
	DOM: CountryAlpha3("DOM"),
	ECU: CountryAlpha3("ECU"),
	EGY: CountryAlpha3("EGY"),
	SLV: CountryAlpha3("SLV"),
	GNQ: CountryAlpha3("GNQ"),
	ERI: CountryAlpha3("ERI"),
	EST: CountryAlpha3("EST"),
	SWZ: CountryAlpha3("SWZ"),
	ETH: CountryAlpha3("ETH"),
	FLK: CountryAlpha3("FLK"),
	FRO: CountryAlpha3("FRO"),
	FJI: CountryAlpha3("FJI"),
	FIN: CountryAlpha3("FIN"),
	FRA: CountryAlpha3("FRA"),
	GUF: CountryAlpha3("GUF"),
	PYF: CountryAlpha3("PYF"),
	ATF: CountryAlpha3("ATF"),
	GAB: CountryAlpha3("GAB"),
	GMB: CountryAlpha3("GMB"),
	GEO: CountryAlpha3("GEO"),
	DEU: CountryAlpha3("DEU"),
	GHA: CountryAlpha3("GHA"),
	GIB: CountryAlpha3("GIB"),
	GRC: CountryAlpha3("GRC"),
	GRL: CountryAlpha3("GRL"),
	GRD: CountryAlpha3("GRD"),
	GLP: CountryAlpha3("GLP"),
	GUM: CountryAlpha3("GUM"),
	GTM: CountryAlpha3("GTM"),
	GGY: CountryAlpha3("GGY"),
	GIN: CountryAlpha3("GIN"),
	GNB: CountryAlpha3("GNB"),
	GUY: CountryAlpha3("GUY"),
	HTI: CountryAlpha3("HTI"),
	HMD: CountryAlpha3("HMD"),
	VAT: CountryAlpha3("VAT"),
	HND: CountryAlpha3("HND"),
	HKG: CountryAlpha3("HKG"),
	HUN: CountryAlpha3("HUN"),
	ISL: CountryAlpha3("ISL"),
	IND: CountryAlpha3("IND"),
	IDN: CountryAlpha3("IDN"),
	IRN: CountryAlpha3("IRN"),
	IRQ: CountryAlpha3("IRQ"),
	IRL: CountryAlpha3("IRL"),
	IMN: CountryAlpha3("IMN"),
	ISR: CountryAlpha3("ISR"),
	ITA: CountryAlpha3("ITA"),
	JAM: CountryAlpha3("JAM"),
	JPN: CountryAlpha3("JPN"),
	JEY: CountryAlpha3("JEY"),
	JOR: CountryAlpha3("JOR"),
	KAZ: CountryAlpha3("KAZ"),
	KEN: CountryAlpha3("KEN"),
	KIR: CountryAlpha3("KIR"),
	PRK: CountryAlpha3("PRK"),
	KOR: CountryAlpha3("KOR"),
	KWT: CountryAlpha3("KWT"),
	KGZ: CountryAlpha3("KGZ"),
	LAO: CountryAlpha3("LAO"),
	LVA: CountryAlpha3("LVA"),
	LBN: CountryAlpha3("LBN"),
	LSO: CountryAlpha3("LSO"),
	LBR: CountryAlpha3("LBR"),
	LBY: CountryAlpha3("LBY"),
	LIE: CountryAlpha3("LIE"),
	LTU: CountryAlpha3("LTU"),
	LUX: CountryAlpha3("LUX"),
	MAC: CountryAlpha3("MAC"),
	MDG: CountryAlpha3("MDG"),
	MWI: CountryAlpha3("MWI"),
	MYS: CountryAlpha3("MYS"),
	MDV: CountryAlpha3("MDV"),
	MLI: CountryAlpha3("MLI"),
	MLT: CountryAlpha3("MLT"),
	MHL: CountryAlpha3("MHL"),
	MTQ: CountryAlpha3("MTQ"),
	MRT: CountryAlpha3("MRT"),
	MUS: CountryAlpha3("MUS"),
	MYT: CountryAlpha3("MYT"),
	MEX: CountryAlpha3("MEX"),
	FSM: CountryAlpha3("FSM"),
	MDA: CountryAlpha3("MDA"),
	MCO: CountryAlpha3("MCO"),
	MNG: CountryAlpha3("MNG"),
	MNE: CountryAlpha3("MNE"),
	MSR: CountryAlpha3("MSR"),
	MAR: CountryAlpha3("MAR"),
	MOZ: CountryAlpha3("MOZ"),
	MMR: CountryAlpha3("MMR"),
	NAM: CountryAlpha3("NAM"),
	NRU: CountryAlpha3("NRU"),
	NPL: CountryAlpha3("NPL"),
	NLD: CountryAlpha3("NLD"),
	NCL: CountryAlpha3("NCL"),
	NZL: CountryAlpha3("NZL"),
	NIC: CountryAlpha3("NIC"),
	NER: CountryAlpha3("NER"),
	NGA: CountryAlpha3("NGA"),
	NIU: CountryAlpha3("NIU"),
	NFK: CountryAlpha3("NFK"),
	MKD: CountryAlpha3("MKD"),
	MNP: CountryAlpha3("MNP"),
	NOR: CountryAlpha3("NOR"),
	OMN: CountryAlpha3("OMN"),
	PAK: CountryAlpha3("PAK"),
	PLW: CountryAlpha3("PLW"),
	PSE: CountryAlpha3("PSE"),
	PAN: CountryAlpha3("PAN"),
	PNG: CountryAlpha3("PNG"),
	PRY: CountryAlpha3("PRY"),
	PER: CountryAlpha3("PER"),
	PHL: CountryAlpha3("PHL"),
	PCN: CountryAlpha3("PCN"),
	POL: CountryAlpha3("POL"),
	PRT: CountryAlpha3("PRT"),
	PRI: CountryAlpha3("PRI"),
	QAT: CountryAlpha3("QAT"),
	REU: CountryAlpha3("REU"),
	ROU: CountryAlpha3("ROU"),
	RUS: CountryAlpha3("RUS"),
	RWA: CountryAlpha3("RWA"),
	BLM: CountryAlpha3("BLM"),
	SHN: CountryAlpha3("SHN"),
	KNA: CountryAlpha3("KNA"),
	LCA: CountryAlpha3("LCA"),
	MAF: CountryAlpha3("MAF"),
	SPM: CountryAlpha3("SPM"),
	VCT: CountryAlpha3("VCT"),
	WSM: CountryAlpha3("WSM"),
	SMR: CountryAlpha3("SMR"),
	STP: CountryAlpha3("STP"),
	SAU: CountryAlpha3("SAU"),
	SEN: CountryAlpha3("SEN"),
	SRB: CountryAlpha3("SRB"),
	SYC: CountryAlpha3("SYC"),
	SLE: CountryAlpha3("SLE"),
	SGP: CountryAlpha3("SGP"),
	SXM: CountryAlpha3("SXM"),
	SVK: CountryAlpha3("SVK"),
	SVN: CountryAlpha3("SVN"),
	SLB: CountryAlpha3("SLB"),
	SOM: CountryAlpha3("SOM"),
	ZAF: CountryAlpha3("ZAF"),
	SGS: CountryAlpha3("SGS"),
	SSD: CountryAlpha3("SSD"),
	ESP: CountryAlpha3("ESP"),
	LKA: CountryAlpha3("LKA"),
	SDN: CountryAlpha3("SDN"),
	SUR: CountryAlpha3("SUR"),
	SJM: CountryAlpha3("SJM"),
	SWE: CountryAlpha3("SWE"),
	CHE: CountryAlpha3("CHE"),
	SYR: CountryAlpha3("SYR"),
	TWN: CountryAlpha3("TWN"),
	TJK: CountryAlpha3("TJK"),
	TZA: CountryAlpha3("TZA"),
	THA: CountryAlpha3("THA"),
	TLS: CountryAlpha3("TLS"),
	TGO: CountryAlpha3("TGO"),
	TKL: CountryAlpha3("TKL"),
	TON: CountryAlpha3("TON"),
	TTO: CountryAlpha3("TTO"),
	TUN: CountryAlpha3("TUN"),
	TUR: CountryAlpha3("TUR"),
	TKM: CountryAlpha3("TKM"),
	TCA: CountryAlpha3("TCA"),
	TUV: CountryAlpha3("TUV"),
	UGA: CountryAlpha3("UGA"),
	UKR: CountryAlpha3("UKR"),
	ARE: CountryAlpha3("ARE"),
	GBR: CountryAlpha3("GBR"),
	UMI: CountryAlpha3("UMI"),
	USA: CountryAlpha3("USA"),
	URY: CountryAlpha3("URY"),
	UZB: CountryAlpha3("UZB"),
	VUT: CountryAlpha3("VUT"),
	VEN: CountryAlpha3("VEN"),
	VNM: CountryAlpha3("VNM"),
	VGB: CountryAlpha3("VGB"),
	VIR: CountryAlpha3("VIR"),
	WLF: CountryAlpha3("WLF"),
	ESH: CountryAlpha3("ESH"),
	YEM: CountryAlpha3("YEM"),
	ZMB: CountryAlpha3("ZMB"),
	ZWE: CountryAlpha3("ZWE"),
	Err: fmt.Errorf("invalid CountryAlpha3"),
}

func init() {
	CountryAlpha3s.Values = []CountryAlpha3{
		CountryAlpha3s.AFG,
		CountryAlpha3s.ALA,
		CountryAlpha3s.ALB,
		CountryAlpha3s.DZA,
		CountryAlpha3s.ASM,
		CountryAlpha3s.AND,
		CountryAlpha3s.AGO,
		CountryAlpha3s.AIA,
		CountryAlpha3s.ATG,
		CountryAlpha3s.ARG,
		CountryAlpha3s.ARM,
		CountryAlpha3s.ABW,
		CountryAlpha3s.AUS,
		CountryAlpha3s.AUT,
		CountryAlpha3s.AZE,
		CountryAlpha3s.BHS,
		CountryAlpha3s.BHR,
		CountryAlpha3s.BGD,
		CountryAlpha3s.BRB,
		CountryAlpha3s.BLR,
		CountryAlpha3s.BEL,
		CountryAlpha3s.BLZ,
		CountryAlpha3s.BEN,
		CountryAlpha3s.BTN,
		CountryAlpha3s.BOL,
		CountryAlpha3s.BES,
		CountryAlpha3s.BIH,
		CountryAlpha3s.BWA,
		CountryAlpha3s.BVT,
		CountryAlpha3s.BRA,
		CountryAlpha3s.IOT,
		CountryAlpha3s.BRN,
		CountryAlpha3s.BGR,
		CountryAlpha3s.BFA,
		CountryAlpha3s.BDI,
		CountryAlpha3s.CPV,
		CountryAlpha3s.KHM,
		CountryAlpha3s.CMR,
		CountryAlpha3s.CAN,
		CountryAlpha3s.CYM,
		CountryAlpha3s.CAF,
		CountryAlpha3s.TCD,
		CountryAlpha3s.CHL,
		CountryAlpha3s.CHN,
		CountryAlpha3s.CXR,
		CountryAlpha3s.CCK,
		CountryAlpha3s.COL,
		CountryAlpha3s.COM,
		CountryAlpha3s.COG,
		CountryAlpha3s.COD,
		CountryAlpha3s.COK,
		CountryAlpha3s.CRI,
		CountryAlpha3s.CIV,
		CountryAlpha3s.HRV,
		CountryAlpha3s.CUB,
		CountryAlpha3s.CUW,
		CountryAlpha3s.CYP,
		CountryAlpha3s.CZE,
		CountryAlpha3s.DNK,
		CountryAlpha3s.DJI,
		CountryAlpha3s.DMA,
		CountryAlpha3s.DOM,
		CountryAlpha3s.ECU,
		CountryAlpha3s.EGY,
		CountryAlpha3s.SLV,
		CountryAlpha3s.GNQ,
		CountryAlpha3s.ERI,
		CountryAlpha3s.EST,
		CountryAlpha3s.SWZ,
		CountryAlpha3s.ETH,
		CountryAlpha3s.FLK,
		CountryAlpha3s.FRO,
		CountryAlpha3s.FJI,
		CountryAlpha3s.FIN,
		CountryAlpha3s.FRA,
		CountryAlpha3s.GUF,
		CountryAlpha3s.PYF,
		CountryAlpha3s.ATF,
		CountryAlpha3s.GAB,
		CountryAlpha3s.GMB,
		CountryAlpha3s.GEO,
		CountryAlpha3s.DEU,
		CountryAlpha3s.GHA,
		CountryAlpha3s.GIB,
		CountryAlpha3s.GRC,
		CountryAlpha3s.GRL,
		CountryAlpha3s.GRD,
		CountryAlpha3s.GLP,
		CountryAlpha3s.GUM,
		CountryAlpha3s.GTM,
		CountryAlpha3s.GGY,
		CountryAlpha3s.GIN,
		CountryAlpha3s.GNB,
		CountryAlpha3s.GUY,
		CountryAlpha3s.HTI,
		CountryAlpha3s.HMD,
		CountryAlpha3s.VAT,
		CountryAlpha3s.HND,
		CountryAlpha3s.HKG,
		CountryAlpha3s.HUN,
		CountryAlpha3s.ISL,
		CountryAlpha3s.IND,
		CountryAlpha3s.IDN,
		CountryAlpha3s.IRN,
		CountryAlpha3s.IRQ,
		CountryAlpha3s.IRL,
		CountryAlpha3s.IMN,
		CountryAlpha3s.ISR,
		CountryAlpha3s.ITA,
		CountryAlpha3s.JAM,
		CountryAlpha3s.JPN,
		CountryAlpha3s.JEY,
		CountryAlpha3s.JOR,
		CountryAlpha3s.KAZ,
		CountryAlpha3s.KEN,
		CountryAlpha3s.KIR,
		CountryAlpha3s.PRK,
		CountryAlpha3s.KOR,
		CountryAlpha3s.KWT,
		CountryAlpha3s.KGZ,
		CountryAlpha3s.LAO,
		CountryAlpha3s.LVA,
		CountryAlpha3s.LBN,
		CountryAlpha3s.LSO,
		CountryAlpha3s.LBR,
		CountryAlpha3s.LBY,
		CountryAlpha3s.LIE,
		CountryAlpha3s.LTU,
		CountryAlpha3s.LUX,
		CountryAlpha3s.MAC,
		CountryAlpha3s.MDG,
		CountryAlpha3s.MWI,
		CountryAlpha3s.MYS,
		CountryAlpha3s.MDV,
		CountryAlpha3s.MLI,
		CountryAlpha3s.MLT,
		CountryAlpha3s.MHL,
		CountryAlpha3s.MTQ,
		CountryAlpha3s.MRT,
		CountryAlpha3s.MUS,
		CountryAlpha3s.MYT,
		CountryAlpha3s.MEX,
		CountryAlpha3s.FSM,
		CountryAlpha3s.MDA,
		CountryAlpha3s.MCO,
		CountryAlpha3s.MNG,
		CountryAlpha3s.MNE,
		CountryAlpha3s.MSR,
		CountryAlpha3s.MAR,
		CountryAlpha3s.MOZ,
		CountryAlpha3s.MMR,
		CountryAlpha3s.NAM,
		CountryAlpha3s.NRU,
		CountryAlpha3s.NPL,
		CountryAlpha3s.NLD,
		CountryAlpha3s.NCL,
		CountryAlpha3s.NZL,
		CountryAlpha3s.NIC,
		CountryAlpha3s.NER,
		CountryAlpha3s.NGA,
		CountryAlpha3s.NIU,
		CountryAlpha3s.NFK,
		CountryAlpha3s.MKD,
		CountryAlpha3s.MNP,
		CountryAlpha3s.NOR,
		CountryAlpha3s.OMN,
		CountryAlpha3s.PAK,
		CountryAlpha3s.PLW,
		CountryAlpha3s.PSE,
		CountryAlpha3s.PAN,
		CountryAlpha3s.PNG,
		CountryAlpha3s.PRY,
		CountryAlpha3s.PER,
		CountryAlpha3s.PHL,
		CountryAlpha3s.PCN,
		CountryAlpha3s.POL,
		CountryAlpha3s.PRT,
		CountryAlpha3s.PRI,
		CountryAlpha3s.QAT,
		CountryAlpha3s.REU,
		CountryAlpha3s.ROU,
		CountryAlpha3s.RUS,
		CountryAlpha3s.RWA,
		CountryAlpha3s.BLM,
		CountryAlpha3s.SHN,
		CountryAlpha3s.KNA,
		CountryAlpha3s.LCA,
		CountryAlpha3s.MAF,
		CountryAlpha3s.SPM,
		CountryAlpha3s.VCT,
		CountryAlpha3s.WSM,
		CountryAlpha3s.SMR,
		CountryAlpha3s.STP,
		CountryAlpha3s.SAU,
		CountryAlpha3s.SEN,
		CountryAlpha3s.SRB,
		CountryAlpha3s.SYC,
		CountryAlpha3s.SLE,
		CountryAlpha3s.SGP,
		CountryAlpha3s.SXM,
		CountryAlpha3s.SVK,
		CountryAlpha3s.SVN,
		CountryAlpha3s.SLB,
		CountryAlpha3s.SOM,
		CountryAlpha3s.ZAF,
		CountryAlpha3s.SGS,
		CountryAlpha3s.SSD,
		CountryAlpha3s.ESP,
		CountryAlpha3s.LKA,
		CountryAlpha3s.SDN,
		CountryAlpha3s.SUR,
		CountryAlpha3s.SJM,
		CountryAlpha3s.SWE,
		CountryAlpha3s.CHE,
		CountryAlpha3s.SYR,
		CountryAlpha3s.TWN,
		CountryAlpha3s.TJK,
		CountryAlpha3s.TZA,
		CountryAlpha3s.THA,
		CountryAlpha3s.TLS,
		CountryAlpha3s.TGO,
		CountryAlpha3s.TKL,
		CountryAlpha3s.TON,
		CountryAlpha3s.TTO,
		CountryAlpha3s.TUN,
		CountryAlpha3s.TUR,
		CountryAlpha3s.TKM,
		CountryAlpha3s.TCA,
		CountryAlpha3s.TUV,
		CountryAlpha3s.UGA,
		CountryAlpha3s.UKR,
		CountryAlpha3s.ARE,
		CountryAlpha3s.GBR,
		CountryAlpha3s.UMI,
		CountryAlpha3s.USA,
		CountryAlpha3s.URY,
		CountryAlpha3s.UZB,
		CountryAlpha3s.VUT,
		CountryAlpha3s.VEN,
		CountryAlpha3s.VNM,
		CountryAlpha3s.VGB,
		CountryAlpha3s.VIR,
		CountryAlpha3s.WLF,
		CountryAlpha3s.ESH,
		CountryAlpha3s.YEM,
		CountryAlpha3s.ZMB,
		CountryAlpha3s.ZWE,
	}
}

func (t countryAlpha3s) newErr(a any, values ...CountryAlpha3) error {
	return fmt.Errorf(
		"invalid %w value '%v'. Must be one of %v",
		CountryAlpha3s.Err,
		a,
		enumer.Join(values, ", "),
	)
}

func (t countryAlpha3s) ParseFrom(v string, values ...CountryAlpha3) (CountryAlpha3, error) {
	var found CountryAlpha3
	var ok bool

	for _, value := range values {
		if enumer.IsEq[string, CountryAlpha3](v)(value) {
			found = value
			ok = true
			break
		}
	}

	if !ok {
		return found, t.newErr(v, values...)
	}

	return found, nil
}

func (t countryAlpha3s) Parse(v string) (CountryAlpha3, error) {
	return t.ParseFrom(v, CountryAlpha3s.Values...)
}

func (t countryAlpha3s) IsFrom(v string, values ...CountryAlpha3) bool {
	for _, value := range values {
		if enumer.IsEq[string, CountryAlpha3](v)(value) {
			return true
		}
	}
	return false
}

func (t countryAlpha3s) Is(v string) bool {
	return t.IsFrom(v, CountryAlpha3s.Values...)
}
