package iso4217

var Currencies = currencies{
	all: []Currency{
		{
			Country: "AFGHANISTAN",
			Name:    "Afghani",
			Code:    "AFN",
			Numeric: "971",
			Units:   "2",
		},
		{
			Country: "ALAND ISLANDS",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "ALBANIA",
			Name:    "Lek",
			Code:    "ALL",
			Numeric: "008",
			Units:   "2",
		},
		{
			Country: "ALGERIA",
			Name:    "Algerian Dinar",
			Code:    "DZD",
			Numeric: "012",
			Units:   "2",
		},
		{
			Country: "AMERICAN SAMOA",
			Name:    "US Dollar",
			Code:    "USD",
			Numeric: "840",
			Units:   "2",
		},
		{
			Country: "ANDORRA",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "ANGOLA",
			Name:    "Kwanza",
			Code:    "AOA",
			Numeric: "973",
			Units:   "2",
		},
		{
			Country: "ANGUILLA",
			Name:    "East Caribbean Dollar",
			Code:    "XCD",
			Numeric: "951",
			Units:   "2",
		},
		{
			Country: "ANTARCTICA",
			Name:    "No universal currency",
			Code:    "",
			Numeric: "",
			Units:   "",
		},
		{
			Country: "ANTIGUA AND BARBUDA",
			Name:    "East Caribbean Dollar",
			Code:    "XCD",
			Numeric: "951",
			Units:   "2",
		},
		{
			Country: "ARAB MONETARY FUND",
			Name:    "Arab Accounting Dinar",
			Code:    "XAD",
			Numeric: "396",
			Units:   "2",
		},
		{
			Country: "ARGENTINA",
			Name:    "Argentine Peso",
			Code:    "ARS",
			Numeric: "032",
			Units:   "2",
		},
		{
			Country: "ARMENIA",
			Name:    "Armenian Dram",
			Code:    "AMD",
			Numeric: "051",
			Units:   "2",
		},
		{
			Country: "ARUBA",
			Name:    "Aruban Florin",
			Code:    "AWG",
			Numeric: "533",
			Units:   "2",
		},
		{
			Country: "AUSTRALIA",
			Name:    "Australian Dollar",
			Code:    "AUD",
			Numeric: "036",
			Units:   "2",
		},
		{
			Country: "AUSTRIA",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "AZERBAIJAN",
			Name:    "Azerbaijan Manat",
			Code:    "AZN",
			Numeric: "944",
			Units:   "2",
		},
		{
			Country: "BAHAMAS (THE)",
			Name:    "Bahamian Dollar",
			Code:    "BSD",
			Numeric: "044",
			Units:   "2",
		},
		{
			Country: "BAHRAIN",
			Name:    "Bahraini Dinar",
			Code:    "BHD",
			Numeric: "048",
			Units:   "3",
		},
		{
			Country: "BANGLADESH",
			Name:    "Taka",
			Code:    "BDT",
			Numeric: "050",
			Units:   "2",
		},
		{
			Country: "BARBADOS",
			Name:    "Barbados Dollar",
			Code:    "BBD",
			Numeric: "052",
			Units:   "2",
		},
		{
			Country: "BELARUS",
			Name:    "Belarusian Ruble",
			Code:    "BYN",
			Numeric: "933",
			Units:   "2",
		},
		{
			Country: "BELGIUM",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "BELIZE",
			Name:    "Belize Dollar",
			Code:    "BZD",
			Numeric: "084",
			Units:   "2",
		},
		{
			Country: "BENIN",
			Name:    "CFA Franc BCEAO",
			Code:    "XOF",
			Numeric: "952",
			Units:   "0",
		},
		{
			Country: "BERMUDA",
			Name:    "Bermudian Dollar",
			Code:    "BMD",
			Numeric: "060",
			Units:   "2",
		},
		{
			Country: "BHUTAN",
			Name:    "Indian Rupee",
			Code:    "INR",
			Numeric: "356",
			Units:   "2",
		},
		{
			Country: "BHUTAN",
			Name:    "Ngultrum",
			Code:    "BTN",
			Numeric: "064",
			Units:   "2",
		},
		{
			Country: "BOLIVIA (PLURINATIONAL STATE OF)",
			Name:    "Boliviano",
			Code:    "BOB",
			Numeric: "068",
			Units:   "2",
		},
		{
			Country: "BOLIVIA (PLURINATIONAL STATE OF)",
			Name:    "Mvdol",
			Code:    "BOV",
			Numeric: "984",
			Units:   "2",
		},
		{
			Country: "BONAIRE, SINT EUSTATIUS AND SABA",
			Name:    "US Dollar",
			Code:    "USD",
			Numeric: "840",
			Units:   "2",
		},
		{
			Country: "BOSNIA AND HERZEGOVINA",
			Name:    "Convertible Mark",
			Code:    "BAM",
			Numeric: "977",
			Units:   "2",
		},
		{
			Country: "BOTSWANA",
			Name:    "Pula",
			Code:    "BWP",
			Numeric: "072",
			Units:   "2",
		},
		{
			Country: "BOUVET ISLAND",
			Name:    "Norwegian Krone",
			Code:    "NOK",
			Numeric: "578",
			Units:   "2",
		},
		{
			Country: "BRAZIL",
			Name:    "Brazilian Real",
			Code:    "BRL",
			Numeric: "986",
			Units:   "2",
		},
		{
			Country: "BRITISH INDIAN OCEAN TERRITORY (THE)",
			Name:    "US Dollar",
			Code:    "USD",
			Numeric: "840",
			Units:   "2",
		},
		{
			Country: "BRUNEI DARUSSALAM",
			Name:    "Brunei Dollar",
			Code:    "BND",
			Numeric: "096",
			Units:   "2",
		},
		{
			Country: "BULGARIA",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "BURKINA FASO",
			Name:    "CFA Franc BCEAO",
			Code:    "XOF",
			Numeric: "952",
			Units:   "0",
		},
		{
			Country: "BURUNDI",
			Name:    "Burundi Franc",
			Code:    "BIF",
			Numeric: "108",
			Units:   "0",
		},
		{
			Country: "CABO VERDE",
			Name:    "Cabo Verde Escudo",
			Code:    "CVE",
			Numeric: "132",
			Units:   "2",
		},
		{
			Country: "CAMBODIA",
			Name:    "Riel",
			Code:    "KHR",
			Numeric: "116",
			Units:   "2",
		},
		{
			Country: "CAMEROON",
			Name:    "CFA Franc BEAC",
			Code:    "XAF",
			Numeric: "950",
			Units:   "0",
		},
		{
			Country: "CANADA",
			Name:    "Canadian Dollar",
			Code:    "CAD",
			Numeric: "124",
			Units:   "2",
		},
		{
			Country: "CAYMAN ISLANDS (THE)",
			Name:    "Cayman Islands Dollar",
			Code:    "KYD",
			Numeric: "136",
			Units:   "2",
		},
		{
			Country: "CENTRAL AFRICAN REPUBLIC (THE)",
			Name:    "CFA Franc BEAC",
			Code:    "XAF",
			Numeric: "950",
			Units:   "0",
		},
		{
			Country: "CHAD",
			Name:    "CFA Franc BEAC",
			Code:    "XAF",
			Numeric: "950",
			Units:   "0",
		},
		{
			Country: "CHILE",
			Name:    "Chilean Peso",
			Code:    "CLP",
			Numeric: "152",
			Units:   "0",
		},
		{
			Country: "CHILE",
			Name:    "Unidad de Fomento",
			Code:    "CLF",
			Numeric: "990",
			Units:   "4",
		},
		{
			Country: "CHINA",
			Name:    "Yuan Renminbi",
			Code:    "CNY",
			Numeric: "156",
			Units:   "2",
		},
		{
			Country: "CHRISTMAS ISLAND",
			Name:    "Australian Dollar",
			Code:    "AUD",
			Numeric: "036",
			Units:   "2",
		},
		{
			Country: "COCOS (KEELING) ISLANDS (THE)",
			Name:    "Australian Dollar",
			Code:    "AUD",
			Numeric: "036",
			Units:   "2",
		},
		{
			Country: "COLOMBIA",
			Name:    "Colombian Peso",
			Code:    "COP",
			Numeric: "170",
			Units:   "2",
		},
		{
			Country: "COLOMBIA",
			Name:    "Unidad de Valor Real",
			Code:    "COU",
			Numeric: "970",
			Units:   "2",
		},
		{
			Country: "COMOROS (THE)",
			Name:    "Comorian Franc ",
			Code:    "KMF",
			Numeric: "174",
			Units:   "0",
		},
		{
			Country: "CONGO (THE DEMOCRATIC REPUBLIC OF THE)",
			Name:    "Congolese Franc",
			Code:    "CDF",
			Numeric: "976",
			Units:   "2",
		},
		{
			Country: "CONGO (THE)",
			Name:    "CFA Franc BEAC",
			Code:    "XAF",
			Numeric: "950",
			Units:   "0",
		},
		{
			Country: "COOK ISLANDS (THE)",
			Name:    "New Zealand Dollar",
			Code:    "NZD",
			Numeric: "554",
			Units:   "2",
		},
		{
			Country: "COSTA RICA",
			Name:    "Costa Rican Colon",
			Code:    "CRC",
			Numeric: "188",
			Units:   "2",
		},
		{
			Country: "COTE D'IVOIRE",
			Name:    "CFA Franc BCEAO",
			Code:    "XOF",
			Numeric: "952",
			Units:   "0",
		},
		{
			Country: "CROATIA",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "CUBA",
			Name:    "Cuban Peso",
			Code:    "CUP",
			Numeric: "192",
			Units:   "2",
		},
		{
			Country: "CURACAO",
			Name:    "Caribbean Guilder",
			Code:    "XCG",
			Numeric: "532",
			Units:   "2",
		},
		{
			Country: "CYPRUS",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "CZECHIA",
			Name:    "Czech Koruna",
			Code:    "CZK",
			Numeric: "203",
			Units:   "2",
		},
		{
			Country: "DENMARK",
			Name:    "Danish Krone",
			Code:    "DKK",
			Numeric: "208",
			Units:   "2",
		},
		{
			Country: "DJIBOUTI",
			Name:    "Djibouti Franc",
			Code:    "DJF",
			Numeric: "262",
			Units:   "0",
		},
		{
			Country: "DOMINICA",
			Name:    "East Caribbean Dollar",
			Code:    "XCD",
			Numeric: "951",
			Units:   "2",
		},
		{
			Country: "DOMINICAN REPUBLIC (THE)",
			Name:    "Dominican Peso",
			Code:    "DOP",
			Numeric: "214",
			Units:   "2",
		},
		{
			Country: "ECUADOR",
			Name:    "US Dollar",
			Code:    "USD",
			Numeric: "840",
			Units:   "2",
		},
		{
			Country: "EGYPT",
			Name:    "Egyptian Pound",
			Code:    "EGP",
			Numeric: "818",
			Units:   "2",
		},
		{
			Country: "EL SALVADOR",
			Name:    "El Salvador Colon",
			Code:    "SVC",
			Numeric: "222",
			Units:   "2",
		},
		{
			Country: "EL SALVADOR",
			Name:    "US Dollar",
			Code:    "USD",
			Numeric: "840",
			Units:   "2",
		},
		{
			Country: "EQUATORIAL GUINEA",
			Name:    "CFA Franc BEAC",
			Code:    "XAF",
			Numeric: "950",
			Units:   "0",
		},
		{
			Country: "ERITREA",
			Name:    "Nakfa",
			Code:    "ERN",
			Numeric: "232",
			Units:   "2",
		},
		{
			Country: "ESTONIA",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "ESWATINI",
			Name:    "Lilangeni",
			Code:    "SZL",
			Numeric: "748",
			Units:   "2",
		},
		{
			Country: "ETHIOPIA",
			Name:    "Ethiopian Birr",
			Code:    "ETB",
			Numeric: "230",
			Units:   "2",
		},
		{
			Country: "EUROPEAN UNION",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "FALKLAND ISLANDS (THE) [MALVINAS]",
			Name:    "Falkland Islands Pound",
			Code:    "FKP",
			Numeric: "238",
			Units:   "2",
		},
		{
			Country: "FAROE ISLANDS (THE)",
			Name:    "Danish Krone",
			Code:    "DKK",
			Numeric: "208",
			Units:   "2",
		},
		{
			Country: "FIJI",
			Name:    "Fiji Dollar",
			Code:    "FJD",
			Numeric: "242",
			Units:   "2",
		},
		{
			Country: "FINLAND",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "FRANCE",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "FRENCH GUIANA",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "FRENCH POLYNESIA",
			Name:    "CFP Franc",
			Code:    "XPF",
			Numeric: "953",
			Units:   "0",
		},
		{
			Country: "FRENCH SOUTHERN TERRITORIES (THE)",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "GABON",
			Name:    "CFA Franc BEAC",
			Code:    "XAF",
			Numeric: "950",
			Units:   "0",
		},
		{
			Country: "GAMBIA (THE)",
			Name:    "Dalasi",
			Code:    "GMD",
			Numeric: "270",
			Units:   "2",
		},
		{
			Country: "GEORGIA",
			Name:    "Lari",
			Code:    "GEL",
			Numeric: "981",
			Units:   "2",
		},
		{
			Country: "GERMANY",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "GHANA",
			Name:    "Ghana Cedi",
			Code:    "GHS",
			Numeric: "936",
			Units:   "2",
		},
		{
			Country: "GIBRALTAR",
			Name:    "Gibraltar Pound",
			Code:    "GIP",
			Numeric: "292",
			Units:   "2",
		},
		{
			Country: "GREECE",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "GREENLAND",
			Name:    "Danish Krone",
			Code:    "DKK",
			Numeric: "208",
			Units:   "2",
		},
		{
			Country: "GRENADA",
			Name:    "East Caribbean Dollar",
			Code:    "XCD",
			Numeric: "951",
			Units:   "2",
		},
		{
			Country: "GUADELOUPE",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "GUAM",
			Name:    "US Dollar",
			Code:    "USD",
			Numeric: "840",
			Units:   "2",
		},
		{
			Country: "GUATEMALA",
			Name:    "Quetzal",
			Code:    "GTQ",
			Numeric: "320",
			Units:   "2",
		},
		{
			Country: "GUERNSEY",
			Name:    "Pound Sterling",
			Code:    "GBP",
			Numeric: "826",
			Units:   "2",
		},
		{
			Country: "GUINEA",
			Name:    "Guinean Franc",
			Code:    "GNF",
			Numeric: "324",
			Units:   "0",
		},
		{
			Country: "GUINEA-BISSAU",
			Name:    "CFA Franc BCEAO",
			Code:    "XOF",
			Numeric: "952",
			Units:   "0",
		},
		{
			Country: "GUYANA",
			Name:    "Guyana Dollar",
			Code:    "GYD",
			Numeric: "328",
			Units:   "2",
		},
		{
			Country: "HAITI",
			Name:    "Gourde",
			Code:    "HTG",
			Numeric: "332",
			Units:   "2",
		},
		{
			Country: "HAITI",
			Name:    "US Dollar",
			Code:    "USD",
			Numeric: "840",
			Units:   "2",
		},
		{
			Country: "HEARD ISLAND AND McDONALD ISLANDS",
			Name:    "Australian Dollar",
			Code:    "AUD",
			Numeric: "036",
			Units:   "2",
		},
		{
			Country: "HOLY SEE (THE)",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "HONDURAS",
			Name:    "Lempira",
			Code:    "HNL",
			Numeric: "340",
			Units:   "2",
		},
		{
			Country: "HONG KONG",
			Name:    "Hong Kong Dollar",
			Code:    "HKD",
			Numeric: "344",
			Units:   "2",
		},
		{
			Country: "HUNGARY",
			Name:    "Forint",
			Code:    "HUF",
			Numeric: "348",
			Units:   "2",
		},
		{
			Country: "ICELAND",
			Name:    "Iceland Krona",
			Code:    "ISK",
			Numeric: "352",
			Units:   "0",
		},
		{
			Country: "INDIA",
			Name:    "Indian Rupee",
			Code:    "INR",
			Numeric: "356",
			Units:   "2",
		},
		{
			Country: "INDONESIA",
			Name:    "Rupiah",
			Code:    "IDR",
			Numeric: "360",
			Units:   "2",
		},
		{
			Country: "INTERNATIONAL MONETARY FUND (IMF)",
			Name:    "SDR (Special Drawing Right)",
			Code:    "XDR",
			Numeric: "960",
			Units:   "N.A.",
		},
		{
			Country: "IRAN (ISLAMIC REPUBLIC OF)",
			Name:    "Iranian Rial",
			Code:    "IRR",
			Numeric: "364",
			Units:   "2",
		},
		{
			Country: "IRAQ",
			Name:    "Iraqi Dinar",
			Code:    "IQD",
			Numeric: "368",
			Units:   "3",
		},
		{
			Country: "IRELAND",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "ISLE OF MAN",
			Name:    "Pound Sterling",
			Code:    "GBP",
			Numeric: "826",
			Units:   "2",
		},
		{
			Country: "ISRAEL",
			Name:    "New Israeli Sheqel",
			Code:    "ILS",
			Numeric: "376",
			Units:   "2",
		},
		{
			Country: "ITALY",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "JAMAICA",
			Name:    "Jamaican Dollar",
			Code:    "JMD",
			Numeric: "388",
			Units:   "2",
		},
		{
			Country: "JAPAN",
			Name:    "Yen",
			Code:    "JPY",
			Numeric: "392",
			Units:   "0",
		},
		{
			Country: "JERSEY",
			Name:    "Pound Sterling",
			Code:    "GBP",
			Numeric: "826",
			Units:   "2",
		},
		{
			Country: "JORDAN",
			Name:    "Jordanian Dinar",
			Code:    "JOD",
			Numeric: "400",
			Units:   "3",
		},
		{
			Country: "KAZAKHSTAN",
			Name:    "Tenge",
			Code:    "KZT",
			Numeric: "398",
			Units:   "2",
		},
		{
			Country: "KENYA",
			Name:    "Kenyan Shilling",
			Code:    "KES",
			Numeric: "404",
			Units:   "2",
		},
		{
			Country: "KIRIBATI",
			Name:    "Australian Dollar",
			Code:    "AUD",
			Numeric: "036",
			Units:   "2",
		},
		{
			Country: "KOREA (THE DEMOCRATIC PEOPLE'S REPUBLIC OF)",
			Name:    "North Korean Won",
			Code:    "KPW",
			Numeric: "408",
			Units:   "2",
		},
		{
			Country: "KOREA (THE REPUBLIC OF)",
			Name:    "Won",
			Code:    "KRW",
			Numeric: "410",
			Units:   "0",
		},
		{
			Country: "KUWAIT",
			Name:    "Kuwaiti Dinar",
			Code:    "KWD",
			Numeric: "414",
			Units:   "3",
		},
		{
			Country: "KYRGYZSTAN",
			Name:    "Som",
			Code:    "KGS",
			Numeric: "417",
			Units:   "2",
		},
		{
			Country: "LAO PEOPLE'S DEMOCRATIC REPUBLIC (THE)",
			Name:    "Lao Kip",
			Code:    "LAK",
			Numeric: "418",
			Units:   "2",
		},
		{
			Country: "LATVIA",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "LEBANON",
			Name:    "Lebanese Pound",
			Code:    "LBP",
			Numeric: "422",
			Units:   "2",
		},
		{
			Country: "LESOTHO",
			Name:    "Loti",
			Code:    "LSL",
			Numeric: "426",
			Units:   "2",
		},
		{
			Country: "LESOTHO",
			Name:    "Rand",
			Code:    "ZAR",
			Numeric: "710",
			Units:   "2",
		},
		{
			Country: "LIBERIA",
			Name:    "Liberian Dollar",
			Code:    "LRD",
			Numeric: "430",
			Units:   "2",
		},
		{
			Country: "LIBYA",
			Name:    "Libyan Dinar",
			Code:    "LYD",
			Numeric: "434",
			Units:   "3",
		},
		{
			Country: "LIECHTENSTEIN",
			Name:    "Swiss Franc",
			Code:    "CHF",
			Numeric: "756",
			Units:   "2",
		},
		{
			Country: "LITHUANIA",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "LUXEMBOURG",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "MACAO",
			Name:    "Pataca",
			Code:    "MOP",
			Numeric: "446",
			Units:   "2",
		},
		{
			Country: "NORTH MACEDONIA",
			Name:    "Denar",
			Code:    "MKD",
			Numeric: "807",
			Units:   "2",
		},
		{
			Country: "MADAGASCAR",
			Name:    "Malagasy Ariary",
			Code:    "MGA",
			Numeric: "969",
			Units:   "2",
		},
		{
			Country: "MALAWI",
			Name:    "Malawi Kwacha",
			Code:    "MWK",
			Numeric: "454",
			Units:   "2",
		},
		{
			Country: "MALAYSIA",
			Name:    "Malaysian Ringgit",
			Code:    "MYR",
			Numeric: "458",
			Units:   "2",
		},
		{
			Country: "MALDIVES",
			Name:    "Rufiyaa",
			Code:    "MVR",
			Numeric: "462",
			Units:   "2",
		},
		{
			Country: "MALI",
			Name:    "CFA Franc BCEAO",
			Code:    "XOF",
			Numeric: "952",
			Units:   "0",
		},
		{
			Country: "MALTA",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "MARSHALL ISLANDS (THE)",
			Name:    "US Dollar",
			Code:    "USD",
			Numeric: "840",
			Units:   "2",
		},
		{
			Country: "MARTINIQUE",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "MAURITANIA",
			Name:    "Ouguiya",
			Code:    "MRU",
			Numeric: "929",
			Units:   "2",
		},
		{
			Country: "MAURITIUS",
			Name:    "Mauritius Rupee",
			Code:    "MUR",
			Numeric: "480",
			Units:   "2",
		},
		{
			Country: "MAYOTTE",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP",
			Name:    "ADB Unit of Account",
			Code:    "XUA",
			Numeric: "965",
			Units:   "N.A.",
		},
		{
			Country: "MEXICO",
			Name:    "Mexican Peso",
			Code:    "MXN",
			Numeric: "484",
			Units:   "2",
		},
		{
			Country: "MEXICO",
			Name:    "Mexican Unidad de Inversion (UDI)",
			Code:    "MXV",
			Numeric: "979",
			Units:   "2",
		},
		{
			Country: "MICRONESIA (FEDERATED STATES OF)",
			Name:    "US Dollar",
			Code:    "USD",
			Numeric: "840",
			Units:   "2",
		},
		{
			Country: "MOLDOVA (THE REPUBLIC OF)",
			Name:    "Moldovan Leu",
			Code:    "MDL",
			Numeric: "498",
			Units:   "2",
		},
		{
			Country: "MONACO",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "MONGOLIA",
			Name:    "Tugrik",
			Code:    "MNT",
			Numeric: "496",
			Units:   "2",
		},
		{
			Country: "MONTENEGRO",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "MONTSERRAT",
			Name:    "East Caribbean Dollar",
			Code:    "XCD",
			Numeric: "951",
			Units:   "2",
		},
		{
			Country: "MOROCCO",
			Name:    "Moroccan Dirham",
			Code:    "MAD",
			Numeric: "504",
			Units:   "2",
		},
		{
			Country: "MOZAMBIQUE",
			Name:    "Mozambique Metical",
			Code:    "MZN",
			Numeric: "943",
			Units:   "2",
		},
		{
			Country: "MYANMAR",
			Name:    "Kyat",
			Code:    "MMK",
			Numeric: "104",
			Units:   "2",
		},
		{
			Country: "NAMIBIA",
			Name:    "Namibia Dollar",
			Code:    "NAD",
			Numeric: "516",
			Units:   "2",
		},
		{
			Country: "NAMIBIA",
			Name:    "Rand",
			Code:    "ZAR",
			Numeric: "710",
			Units:   "2",
		},
		{
			Country: "NAURU",
			Name:    "Australian Dollar",
			Code:    "AUD",
			Numeric: "036",
			Units:   "2",
		},
		{
			Country: "NEPAL",
			Name:    "Nepalese Rupee",
			Code:    "NPR",
			Numeric: "524",
			Units:   "2",
		},
		{
			Country: "NETHERLANDS (THE)",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "NEW CALEDONIA",
			Name:    "CFP Franc",
			Code:    "XPF",
			Numeric: "953",
			Units:   "0",
		},
		{
			Country: "NEW ZEALAND",
			Name:    "New Zealand Dollar",
			Code:    "NZD",
			Numeric: "554",
			Units:   "2",
		},
		{
			Country: "NICARAGUA",
			Name:    "Cordoba Oro",
			Code:    "NIO",
			Numeric: "558",
			Units:   "2",
		},
		{
			Country: "NIGER (THE)",
			Name:    "CFA Franc BCEAO",
			Code:    "XOF",
			Numeric: "952",
			Units:   "0",
		},
		{
			Country: "NIGERIA",
			Name:    "Naira",
			Code:    "NGN",
			Numeric: "566",
			Units:   "2",
		},
		{
			Country: "NIUE",
			Name:    "New Zealand Dollar",
			Code:    "NZD",
			Numeric: "554",
			Units:   "2",
		},
		{
			Country: "NORFOLK ISLAND",
			Name:    "Australian Dollar",
			Code:    "AUD",
			Numeric: "036",
			Units:   "2",
		},
		{
			Country: "NORTHERN MARIANA ISLANDS (THE)",
			Name:    "US Dollar",
			Code:    "USD",
			Numeric: "840",
			Units:   "2",
		},
		{
			Country: "NORWAY",
			Name:    "Norwegian Krone",
			Code:    "NOK",
			Numeric: "578",
			Units:   "2",
		},
		{
			Country: "OMAN",
			Name:    "Rial Omani",
			Code:    "OMR",
			Numeric: "512",
			Units:   "3",
		},
		{
			Country: "PAKISTAN",
			Name:    "Pakistan Rupee",
			Code:    "PKR",
			Numeric: "586",
			Units:   "2",
		},
		{
			Country: "PALAU",
			Name:    "US Dollar",
			Code:    "USD",
			Numeric: "840",
			Units:   "2",
		},
		{
			Country: "PALESTINE, STATE OF",
			Name:    "No universal currency",
			Code:    "",
			Numeric: "",
			Units:   "",
		},
		{
			Country: "PANAMA",
			Name:    "Balboa",
			Code:    "PAB",
			Numeric: "590",
			Units:   "2",
		},
		{
			Country: "PANAMA",
			Name:    "US Dollar",
			Code:    "USD",
			Numeric: "840",
			Units:   "2",
		},
		{
			Country: "PAPUA NEW GUINEA",
			Name:    "Kina",
			Code:    "PGK",
			Numeric: "598",
			Units:   "2",
		},
		{
			Country: "PARAGUAY",
			Name:    "Guarani",
			Code:    "PYG",
			Numeric: "600",
			Units:   "0",
		},
		{
			Country: "PERU",
			Name:    "Sol",
			Code:    "PEN",
			Numeric: "604",
			Units:   "2",
		},
		{
			Country: "PHILIPPINES (THE)",
			Name:    "Philippine Peso",
			Code:    "PHP",
			Numeric: "608",
			Units:   "2",
		},
		{
			Country: "PITCAIRN",
			Name:    "New Zealand Dollar",
			Code:    "NZD",
			Numeric: "554",
			Units:   "2",
		},
		{
			Country: "POLAND",
			Name:    "Zloty",
			Code:    "PLN",
			Numeric: "985",
			Units:   "2",
		},
		{
			Country: "PORTUGAL",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "PUERTO RICO",
			Name:    "US Dollar",
			Code:    "USD",
			Numeric: "840",
			Units:   "2",
		},
		{
			Country: "QATAR",
			Name:    "Qatari Rial",
			Code:    "QAR",
			Numeric: "634",
			Units:   "2",
		},
		{
			Country: "RÉUNION",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "ROMANIA",
			Name:    "Romanian Leu",
			Code:    "RON",
			Numeric: "946",
			Units:   "2",
		},
		{
			Country: "RUSSIAN FEDERATION (THE)",
			Name:    "Russian Ruble",
			Code:    "RUB",
			Numeric: "643",
			Units:   "2",
		},
		{
			Country: "RWANDA",
			Name:    "Rwanda Franc",
			Code:    "RWF",
			Numeric: "646",
			Units:   "0",
		},
		{
			Country: "SAINT BARTHÉLEMY",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA",
			Name:    "Saint Helena Pound",
			Code:    "SHP",
			Numeric: "654",
			Units:   "2",
		},
		{
			Country: "SAINT KITTS AND NEVIS",
			Name:    "East Caribbean Dollar",
			Code:    "XCD",
			Numeric: "951",
			Units:   "2",
		},
		{
			Country: "SAINT LUCIA",
			Name:    "East Caribbean Dollar",
			Code:    "XCD",
			Numeric: "951",
			Units:   "2",
		},
		{
			Country: "SAINT MARTIN (FRENCH PART)",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "SAINT PIERRE AND MIQUELON",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "SAINT VINCENT AND THE GRENADINES",
			Name:    "East Caribbean Dollar",
			Code:    "XCD",
			Numeric: "951",
			Units:   "2",
		},
		{
			Country: "SAMOA",
			Name:    "Tala",
			Code:    "WST",
			Numeric: "882",
			Units:   "2",
		},
		{
			Country: "SAN MARINO",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "SAO TOME AND PRINCIPE",
			Name:    "Dobra",
			Code:    "STN",
			Numeric: "930",
			Units:   "2",
		},
		{
			Country: "SAUDI ARABIA",
			Name:    "Saudi Riyal",
			Code:    "SAR",
			Numeric: "682",
			Units:   "2",
		},
		{
			Country: "SENEGAL",
			Name:    "CFA Franc BCEAO",
			Code:    "XOF",
			Numeric: "952",
			Units:   "0",
		},
		{
			Country: "SERBIA",
			Name:    "Serbian Dinar",
			Code:    "RSD",
			Numeric: "941",
			Units:   "2",
		},
		{
			Country: "SEYCHELLES",
			Name:    "Seychelles Rupee",
			Code:    "SCR",
			Numeric: "690",
			Units:   "2",
		},
		{
			Country: "SIERRA LEONE",
			Name:    "Leone",
			Code:    "SLE",
			Numeric: "925",
			Units:   "2",
		},
		{
			Country: "SINGAPORE",
			Name:    "Singapore Dollar",
			Code:    "SGD",
			Numeric: "702",
			Units:   "2",
		},
		{
			Country: "SINT MAARTEN (DUTCH PART)",
			Name:    "Caribbean Guilder",
			Code:    "XCG",
			Numeric: "532",
			Units:   "2",
		},
		{
			Country: "SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS &#34;SUCRE&#34;",
			Name:    "Sucre",
			Code:    "XSU",
			Numeric: "994",
			Units:   "N.A.",
		},
		{
			Country: "SLOVAKIA",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "SLOVENIA",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "SOLOMON ISLANDS",
			Name:    "Solomon Islands Dollar",
			Code:    "SBD",
			Numeric: "090",
			Units:   "2",
		},
		{
			Country: "SOMALIA",
			Name:    "Somali Shilling",
			Code:    "SOS",
			Numeric: "706",
			Units:   "2",
		},
		{
			Country: "SOUTH AFRICA",
			Name:    "Rand",
			Code:    "ZAR",
			Numeric: "710",
			Units:   "2",
		},
		{
			Country: "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
			Name:    "No universal currency",
			Code:    "",
			Numeric: "",
			Units:   "",
		},
		{
			Country: "SOUTH SUDAN",
			Name:    "South Sudanese Pound",
			Code:    "SSP",
			Numeric: "728",
			Units:   "2",
		},
		{
			Country: "SPAIN",
			Name:    "Euro",
			Code:    "EUR",
			Numeric: "978",
			Units:   "2",
		},
		{
			Country: "SRI LANKA",
			Name:    "Sri Lanka Rupee",
			Code:    "LKR",
			Numeric: "144",
			Units:   "2",
		},
		{
			Country: "SUDAN (THE)",
			Name:    "Sudanese Pound",
			Code:    "SDG",
			Numeric: "938",
			Units:   "2",
		},
		{
			Country: "SURINAME",
			Name:    "Surinam Dollar",
			Code:    "SRD",
			Numeric: "968",
			Units:   "2",
		},
		{
			Country: "SVALBARD AND JAN MAYEN",
			Name:    "Norwegian Krone",
			Code:    "NOK",
			Numeric: "578",
			Units:   "2",
		},
		{
			Country: "SWEDEN",
			Name:    "Swedish Krona",
			Code:    "SEK",
			Numeric: "752",
			Units:   "2",
		},
		{
			Country: "SWITZERLAND",
			Name:    "Swiss Franc",
			Code:    "CHF",
			Numeric: "756",
			Units:   "2",
		},
		{
			Country: "SWITZERLAND",
			Name:    "WIR Euro",
			Code:    "CHE",
			Numeric: "947",
			Units:   "2",
		},
		{
			Country: "SWITZERLAND",
			Name:    "WIR Franc",
			Code:    "CHW",
			Numeric: "948",
			Units:   "2",
		},
		{
			Country: "SYRIAN ARAB REPUBLIC",
			Name:    "Syrian Pound",
			Code:    "SYP",
			Numeric: "760",
			Units:   "2",
		},
		{
			Country: "TAIWAN (PROVINCE OF CHINA)",
			Name:    "New Taiwan Dollar",
			Code:    "TWD",
			Numeric: "901",
			Units:   "2",
		},
		{
			Country: "TAJIKISTAN",
			Name:    "Somoni",
			Code:    "TJS",
			Numeric: "972",
			Units:   "2",
		},
		{
			Country: "TANZANIA, UNITED REPUBLIC OF",
			Name:    "Tanzanian Shilling",
			Code:    "TZS",
			Numeric: "834",
			Units:   "2",
		},
		{
			Country: "THAILAND",
			Name:    "Baht",
			Code:    "THB",
			Numeric: "764",
			Units:   "2",
		},
		{
			Country: "TIMOR-LESTE",
			Name:    "US Dollar",
			Code:    "USD",
			Numeric: "840",
			Units:   "2",
		},
		{
			Country: "TOGO",
			Name:    "CFA Franc BCEAO",
			Code:    "XOF",
			Numeric: "952",
			Units:   "0",
		},
		{
			Country: "TOKELAU",
			Name:    "New Zealand Dollar",
			Code:    "NZD",
			Numeric: "554",
			Units:   "2",
		},
		{
			Country: "TONGA",
			Name:    "Pa’anga",
			Code:    "TOP",
			Numeric: "776",
			Units:   "2",
		},
		{
			Country: "TRINIDAD AND TOBAGO",
			Name:    "Trinidad and Tobago Dollar",
			Code:    "TTD",
			Numeric: "780",
			Units:   "2",
		},
		{
			Country: "TUNISIA",
			Name:    "Tunisian Dinar",
			Code:    "TND",
			Numeric: "788",
			Units:   "3",
		},
		{
			Country: "TÜRKİYE",
			Name:    "Turkish Lira",
			Code:    "TRY",
			Numeric: "949",
			Units:   "2",
		},
		{
			Country: "TURKMENISTAN",
			Name:    "Turkmenistan New Manat",
			Code:    "TMT",
			Numeric: "934",
			Units:   "2",
		},
		{
			Country: "TURKS AND CAICOS ISLANDS (THE)",
			Name:    "US Dollar",
			Code:    "USD",
			Numeric: "840",
			Units:   "2",
		},
		{
			Country: "TUVALU",
			Name:    "Australian Dollar",
			Code:    "AUD",
			Numeric: "036",
			Units:   "2",
		},
		{
			Country: "UGANDA",
			Name:    "Uganda Shilling",
			Code:    "UGX",
			Numeric: "800",
			Units:   "0",
		},
		{
			Country: "UKRAINE",
			Name:    "Hryvnia",
			Code:    "UAH",
			Numeric: "980",
			Units:   "2",
		},
		{
			Country: "UNITED ARAB EMIRATES (THE)",
			Name:    "UAE Dirham",
			Code:    "AED",
			Numeric: "784",
			Units:   "2",
		},
		{
			Country: "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)",
			Name:    "Pound Sterling",
			Code:    "GBP",
			Numeric: "826",
			Units:   "2",
		},
		{
			Country: "UNITED STATES MINOR OUTLYING ISLANDS (THE)",
			Name:    "US Dollar",
			Code:    "USD",
			Numeric: "840",
			Units:   "2",
		},
		{
			Country: "UNITED STATES OF AMERICA (THE)",
			Name:    "US Dollar",
			Code:    "USD",
			Numeric: "840",
			Units:   "2",
		},
		{
			Country: "UNITED STATES OF AMERICA (THE)",
			Name:    "US Dollar (Next day)",
			Code:    "USN",
			Numeric: "997",
			Units:   "2",
		},
		{
			Country: "URUGUAY",
			Name:    "Peso Uruguayo",
			Code:    "UYU",
			Numeric: "858",
			Units:   "2",
		},
		{
			Country: "URUGUAY",
			Name:    "Uruguay Peso en Unidades Indexadas (UI)",
			Code:    "UYI",
			Numeric: "940",
			Units:   "0",
		},
		{
			Country: "URUGUAY",
			Name:    "Unidad Previsional",
			Code:    "UYW",
			Numeric: "927",
			Units:   "4",
		},
		{
			Country: "UZBEKISTAN",
			Name:    "Uzbekistan Sum",
			Code:    "UZS",
			Numeric: "860",
			Units:   "2",
		},
		{
			Country: "VANUATU",
			Name:    "Vatu",
			Code:    "VUV",
			Numeric: "548",
			Units:   "0",
		},
		{
			Country: "VENEZUELA (BOLIVARIAN REPUBLIC OF)",
			Name:    "Bolívar Soberano",
			Code:    "VES",
			Numeric: "928",
			Units:   "2",
		},
		{
			Country: "VENEZUELA (BOLIVARIAN REPUBLIC OF)",
			Name:    "Bolívar Soberano",
			Code:    "VED",
			Numeric: "926",
			Units:   "2",
		},
		{
			Country: "VIET NAM",
			Name:    "Dong",
			Code:    "VND",
			Numeric: "704",
			Units:   "0",
		},
		{
			Country: "VIRGIN ISLANDS (BRITISH)",
			Name:    "US Dollar",
			Code:    "USD",
			Numeric: "840",
			Units:   "2",
		},
		{
			Country: "VIRGIN ISLANDS (U.S.)",
			Name:    "US Dollar",
			Code:    "USD",
			Numeric: "840",
			Units:   "2",
		},
		{
			Country: "WALLIS AND FUTUNA",
			Name:    "CFP Franc",
			Code:    "XPF",
			Numeric: "953",
			Units:   "0",
		},
		{
			Country: "WESTERN SAHARA",
			Name:    "Moroccan Dirham",
			Code:    "MAD",
			Numeric: "504",
			Units:   "2",
		},
		{
			Country: "YEMEN",
			Name:    "Yemeni Rial",
			Code:    "YER",
			Numeric: "886",
			Units:   "2",
		},
		{
			Country: "ZAMBIA",
			Name:    "Zambian Kwacha",
			Code:    "ZMW",
			Numeric: "967",
			Units:   "2",
		},
		{
			Country: "ZIMBABWE",
			Name:    "Zimbabwe Gold",
			Code:    "ZWG",
			Numeric: "924",
			Units:   "2",
		},
		{
			Country: "ZZ01_Bond Markets Unit European_EURCO",
			Name:    "Bond Markets Unit European Composite Unit (EURCO)",
			Code:    "XBA",
			Numeric: "955",
			Units:   "N.A.",
		},
		{
			Country: "ZZ02_Bond Markets Unit European_EMU-6",
			Name:    "Bond Markets Unit European Monetary Unit (E.M.U.-6)",
			Code:    "XBB",
			Numeric: "956",
			Units:   "N.A.",
		},
		{
			Country: "ZZ03_Bond Markets Unit European_EUA-9",
			Name:    "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)",
			Code:    "XBC",
			Numeric: "957",
			Units:   "N.A.",
		},
		{
			Country: "ZZ04_Bond Markets Unit European_EUA-17",
			Name:    "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)",
			Code:    "XBD",
			Numeric: "958",
			Units:   "N.A.",
		},
		{
			Country: "ZZ06_Testing_Code",
			Name:    "Codes specifically reserved for testing purposes",
			Code:    "XTS",
			Numeric: "963",
			Units:   "N.A.",
		},
		{
			Country: "ZZ07_No_Currency",
			Name:    "The codes assigned for transactions where no currency is involved",
			Code:    "XXX",
			Numeric: "999",
			Units:   "N.A.",
		},
		{
			Country: "ZZ08_Gold",
			Name:    "Gold",
			Code:    "XAU",
			Numeric: "959",
			Units:   "N.A.",
		},
		{
			Country: "ZZ09_Palladium",
			Name:    "Palladium",
			Code:    "XPD",
			Numeric: "964",
			Units:   "N.A.",
		},
		{
			Country: "ZZ10_Platinum",
			Name:    "Platinum",
			Code:    "XPT",
			Numeric: "962",
			Units:   "N.A.",
		},
		{
			Country: "ZZ11_Silver",
			Name:    "Silver",
			Code:    "XAG",
			Numeric: "961",
			Units:   "N.A.",
		},
	},
}
