package quantity

type Kind string

type kinds struct {
	Unknown                         Kind
	Time                            Kind
	Length                          Kind
	Mass                            Kind
	ElectricCurrent                 Kind
	Temperature                     Kind
	AmountOfSubstance               Kind
	LuminousIntensity               Kind
	PlaneAngle                      Kind
	SolidAngle                      Kind
	Force                           Kind
	Frequency                       Kind
	Pressure                        Kind
	Stress                          Kind
	Energy                          Kind
	Work                            Kind
	AmountOfHeat                    Kind
	Power                           Kind
	RadiantFlux                     Kind
	ElectricCharge                  Kind
	ElectricPotential               Kind
	ElectricResistance              Kind
	ElectricConductance             Kind
	ElectricCapacitance             Kind
	ElectricInductance              Kind
	MagneticFluxDensity             Kind
	MagneticFlux                    Kind
	LuminousFlux                    Kind
	Illuminance                     Kind
	ActivityOfARadioactiveSubstance Kind
	AbsorbedDose                    Kind
	Kerma                           Kind
	DoseEquivalent                  Kind
	AcatalyticActivity              Kind
	Area                            Kind
	Volume                          Kind
	Speed                           Kind
	Velocity                        Kind
	Acceleration                    Kind
	Density                         Kind
	WaveNumber                      Kind
	SurfaceDensity                  Kind
	SpecificVolume                  Kind
	CurrentDensity                  Kind
	MagneticFieldStrength           Kind
	MassConcentration               Kind
	Luminance                       Kind
	DynamicViscosity                Kind
	MomentOfForce                   Kind
	SurfaceTension                  Kind
	AngularVelocity                 Kind
	AngularFrequency                Kind
	AngularAcceleration             Kind
	HeatFluxDensity                 Kind
	Irradiance                      Kind
	Entropy                         Kind
	HeatCapacity                    Kind
	SpecificHeatCapacity            Kind
	SpecificEntropy                 Kind
	SpecificEnergy                  Kind
	ThermalConductivity             Kind
	EngeryDensity                   Kind
	ElectricFieldStrength           Kind
	ElectricChargeDensity           Kind
}

var Kinds = kinds{
	Unknown:                         "measurement.quantity.unknown",
	Time:                            "measurement.quantity.time",
	Length:                          "measurement.quantity.length",
	Mass:                            "measurement.quantity.mass",
	ElectricCurrent:                 "measurement.quantity.electric-current",
	Temperature:                     "measurement.quantity.temperature",
	AmountOfSubstance:               "measurement.quantity.amount-of-substance",
	LuminousIntensity:               "measurement.quantity.luminous-intensity",
	PlaneAngle:                      "measurement.quantity.plane-angle",
	SolidAngle:                      "measurement.quantity.solid-angle",
	Frequency:                       "measurement.quantity.frequency",
	Energy:                          "measurement.quantity.energy",
	Work:                            "measurement.quantity.work",
	AmountOfHeat:                    "measurement.quantity.amount-of-heat",
	Power:                           "measurement.quantity.power",
	RadiantFlux:                     "measurement.quantity.radiant-flux",
	ElectricPotential:               "measurement.quantity.electric-potential",
	ElectricCapacitance:             "measurement.quantity.electric-capacitance",
	ElectricInductance:              "measurement.quantity.electric-inductance",
	ElectricCharge:                  "measurement.quantity.electric-charge",
	LuminousFlux:                    "measurement.quantity.luminous-flux",
	Illuminance:                     "measurement.quantity.illuminance",
	ActivityOfARadioactiveSubstance: "measurement.quantity.activity-of-a-radioactive-substance",
	AbsorbedDose:                    "measurement.quantity.absorbed-dose",
	Kerma:                           "measurement.quantity.kerma",
	DoseEquivalent:                  "measurement.quantity.dose-equivalent",
	AcatalyticActivity:              "measurement.quantity.acatalytic-activity",
	Area:                            "measurement.quantity.area",
	Volume:                          "measurement.quantity.volume",
	Speed:                           "measurement.quantity.speed",
	Acceleration:                    "measurement.quantity.acceleration",
	Density:                         "measurement.quantity.density",
	Force:                           "measurement.quantity.force",
	Pressure:                        "measurement.quantity.pressure",
	ElectricResistance:              "measurement.quantity.electric-resistance",
	ElectricConductance:             "measurement.quantity.electric-conductance",
	MagneticFluxDensity:             "measurement.quantity.magnetic-flux-density",
	MagneticFlux:                    "measurement.quantity.magnetic-flux",
	Stress:                          "measurement.quantity.stress",
	Velocity:                        "measurement.quantity.velocity",
	WaveNumber:                      "measurement.quantity.wave-number",
	SurfaceDensity:                  "measurement.quantity.surface-density",
	SpecificVolume:                  "measurement.quantity.specific-volume",
	CurrentDensity:                  "measurement.quantity.current-density",
	MagneticFieldStrength:           "measurement.quantity.magnetic-field-strength",
	MassConcentration:               "measurement.quantity.mass-concentration",
	Luminance:                       "measurement.quantity.luminance",
	DynamicViscosity:                "measurement.quantity.dynamic-viscosity",
	MomentOfForce:                   "measurement.quantity.moment-of-force",
	SurfaceTension:                  "measurement.quantity.surface-tension",
	AngularVelocity:                 "measurement.quantity.angular-velocity",
	AngularFrequency:                "measurement.quantity.angular-frequency",
	AngularAcceleration:             "measurement.quantity.angular-acceleration",
	HeatFluxDensity:                 "measurement.quantity.heat-flux-density",
	Irradiance:                      "measurement.quantity.irradiance",
	Entropy:                         "measurement.quantity.entropy",
	HeatCapacity:                    "measurement.quantity.heat-capacity",
	SpecificHeatCapacity:            "measurement.quantity.specific-heat-capacity",
	SpecificEntropy:                 "measurement.quantity.specific-entropy",
	SpecificEnergy:                  "measurement.quantity.specific-energy",
	ThermalConductivity:             "measurement.quantity.thermal-conductivity",
	EngeryDensity:                   "measurement.quantity.engery-density",
	ElectricFieldStrength:           "measurement.quantity.electric-field-strength",
	ElectricChargeDensity:           "measurement.quantity.electric-charge-density",
}
