// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package affix

import (
	"database/sql"

	"github.com/boundedinfinity/canonical-model/go/idiomatic/ider"
)

type AffixCategory struct {
	ID          ider.Id
	Name        string
	Description sql.NullString
}
