// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package affix

import (
	"context"

	"github.com/boundedinfinity/canonical-model/go/idiomatic/ider"
)

const getCategory = `-- name: GetCategory :one
SELECT id, 'name', 'description' FROM affix_category
WHERE id = ?
`

func (q *Queries) GetCategory(ctx context.Context, id ider.Id) (AffixCategory, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i AffixCategory
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}
