//************************************************************************************
//*                                                                                  *
//* ===== DO NOT EDIT =====                                                          *
//* Manual changes will be overwritten.                                              *
//* Generated by github.com/boundedinfinity/enumer                                   *
//*                                                                                  *
//************************************************************************************

package people

import (
	"database/sql/driver"
	"encoding/xml"
	"fmt"

	"github.com/boundedinfinity/enumer"
)

type PrefixFormat string

// /////////////////////////////////////////////////////////////////
//  PrefixFormat Stringer implemenation
// /////////////////////////////////////////////////////////////////

func (t PrefixFormat) String() string {
	return string(t)
}

// /////////////////////////////////////////////////////////////////
//  PrefixFormat JSON marshal/unmarshal implemenation
// /////////////////////////////////////////////////////////////////

func (t PrefixFormat) MarshalJSON() ([]byte, error) {
	return enumer.MarshalJSON(t)
}

func (t *PrefixFormat) UnmarshalJSON(data []byte) error {
	return enumer.UnmarshalJSON(data, t, PrefixFormats.Parse)
}

// /////////////////////////////////////////////////////////////////
//  PrefixFormat YAML marshal/unmarshal implemenation
// /////////////////////////////////////////////////////////////////

func (t PrefixFormat) MarshalYAML() (interface{}, error) {
	return enumer.MarshalYAML(t)
}

func (t *PrefixFormat) UnmarshalYAML(unmarshal func(interface{}) error) error {
	return enumer.UnmarshalYAML(unmarshal, t, PrefixFormats.Parse)
}

// /////////////////////////////////////////////////////////////////
//  PrefixFormat XML marshal/unmarshal implemenation
// /////////////////////////////////////////////////////////////////

func (t PrefixFormat) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return enumer.MarshalXML(t, e, start)
}

func (t *PrefixFormat) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return enumer.UnmarshalXML(t, PrefixFormats.Parse, d, start)
}

// /////////////////////////////////////////////////////////////////
//  PrefixFormat SQL Database marshal/unmarshal implemenation
// /////////////////////////////////////////////////////////////////

func (t PrefixFormat) Value() (driver.Value, error) {
	return enumer.Value(t)
}

func (t *PrefixFormat) Scan(value interface{}) error {
	return enumer.Scan(value, t, PrefixFormats.Parse)
}

// /////////////////////////////////////////////////////////////////
//
//  Enumeration
//
// /////////////////////////////////////////////////////////////////

type prefixFormats struct {
	Full         PrefixFormat
	Abbreviation PrefixFormat
	Values       []PrefixFormat
	Err          error
}

var PrefixFormats = prefixFormats{
	Full:         PrefixFormat("full"),
	Abbreviation: PrefixFormat("abbreviation"),
	Err:          fmt.Errorf("invalid PrefixFormat"),
}

func init() {
	PrefixFormats.Values = []PrefixFormat{
		PrefixFormats.Full,
		PrefixFormats.Abbreviation,
	}
}

func (t prefixFormats) newErr(a any, values ...PrefixFormat) error {
	return fmt.Errorf(
		"invalid %w value '%v'. Must be one of %v",
		PrefixFormats.Err,
		a,
		enumer.Join(values, ", "),
	)
}

func (t prefixFormats) ParseFrom(v string, values ...PrefixFormat) (PrefixFormat, error) {
	var found PrefixFormat
	var ok bool

	for _, value := range values {
		if enumer.IsEq[string, PrefixFormat](v)(value) {
			found = value
			ok = true
			break
		}
	}

	if !ok {
		return found, t.newErr(v, values...)
	}

	return found, nil
}

func (t prefixFormats) Parse(v string) (PrefixFormat, error) {
	return t.ParseFrom(v, PrefixFormats.Values...)
}

func (t prefixFormats) IsFrom(v string, values ...PrefixFormat) bool {
	for _, value := range values {
		if enumer.IsEq[string, PrefixFormat](v)(value) {
			return true
		}
	}
	return false
}

func (t prefixFormats) Is(v string) bool {
	return t.IsFrom(v, PrefixFormats.Values...)
}
