//************************************************************************************
//*                                                                                  *
//* ===== DO NOT EDIT =====                                                          *
//* Manual changes will be overwritten.                                              *
//* Generated by github.com/boundedinfinity/enumer                                   *
//*                                                                                  *
//************************************************************************************

package phone

import (
	"database/sql/driver"
	"fmt"

	"github.com/boundedinfinity/enumer"
)

type NanpPhoneFormat string

// /////////////////////////////////////////////////////////////////
//  NanpPhoneFormat Stringer implemenation
// /////////////////////////////////////////////////////////////////

func (t NanpPhoneFormat) String() string {
	return string(t)
}

// /////////////////////////////////////////////////////////////////
//  NanpPhoneFormat JSON marshal/unmarshal implemenation
// /////////////////////////////////////////////////////////////////

func (t NanpPhoneFormat) MarshalJSON() ([]byte, error) {
	return enumer.MarshalJSON(t)
}

func (t *NanpPhoneFormat) UnmarshalJSON(data []byte) error {
	return enumer.UnmarshalJSON(data, t, NanpPhoneFormats.Parse)
}

// /////////////////////////////////////////////////////////////////
//  NanpPhoneFormat YAML marshal/unmarshal implemenation
// /////////////////////////////////////////////////////////////////

func (t NanpPhoneFormat) MarshalYAML() (interface{}, error) {
	return enumer.MarshalYAML(t)
}

func (t *NanpPhoneFormat) UnmarshalYAML(unmarshal func(interface{}) error) error {
	return enumer.UnmarshalYAML(unmarshal, t, NanpPhoneFormats.Parse)
}

// /////////////////////////////////////////////////////////////////
//  NanpPhoneFormat SQL Database marshal/unmarshal implemenation
// /////////////////////////////////////////////////////////////////

func (t NanpPhoneFormat) Value() (driver.Value, error) {
	return enumer.Value(t)
}

func (t *NanpPhoneFormat) Scan(value interface{}) error {
	return enumer.Scan(value, t, NanpPhoneFormats.Parse)
}

// /////////////////////////////////////////////////////////////////
//
//  Enumeration
//
// /////////////////////////////////////////////////////////////////

type nanpPhoneFormats struct {
	Full   NanpPhoneFormat
	Common NanpPhoneFormat
	Values []NanpPhoneFormat
	Err    error
}

var NanpPhoneFormats = nanpPhoneFormats{
	Full:   NanpPhoneFormat("full"),
	Common: NanpPhoneFormat("common"),
	Err:    fmt.Errorf("invalid NanpPhoneFormat"),
}

func init() {
	NanpPhoneFormats.Values = []NanpPhoneFormat{
		NanpPhoneFormats.Full,
		NanpPhoneFormats.Common,
	}
}

func (t nanpPhoneFormats) newErr(a any, values ...NanpPhoneFormat) error {
	return fmt.Errorf(
		"invalid %w value '%v'. Must be one of %v",
		NanpPhoneFormats.Err,
		a,
		enumer.Join(values, ", "),
	)
}

func (t nanpPhoneFormats) ParseFrom(v string, values ...NanpPhoneFormat) (NanpPhoneFormat, error) {
	var found NanpPhoneFormat
	var ok bool

	for _, value := range values {
		if enumer.IsEq[string, NanpPhoneFormat](v)(value) {
			found = value
			ok = true
			break
		}
	}

	if !ok {
		return found, t.newErr(v, values...)
	}

	return found, nil
}

func (t nanpPhoneFormats) Parse(v string) (NanpPhoneFormat, error) {
	return t.ParseFrom(v, NanpPhoneFormats.Values...)
}

func (t nanpPhoneFormats) IsFrom(v string, values ...NanpPhoneFormat) bool {
	for _, value := range values {
		if enumer.IsEq[string, NanpPhoneFormat](v)(value) {
			return true
		}
	}
	return false
}

func (t nanpPhoneFormats) Is(v string) bool {
	return t.IsFrom(v, NanpPhoneFormats.Values...)
}
